### PR TITLE
Change rockspec URL to git+https

### PR DESCRIPTION
**Pull request by Frenzie**
Resolves this error:

```
Cloning into 'busted'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

Cf. <https://github.com/Olivine-Labs/busted/issues/668#issuecomment-1073215957>.

### CODE REVIEW

**Comment by Tieske** [comment]
unfortunately all existing rockspecs must also be updated, and re-uploaded

**Comment by alerque** [comment]
Yes, this is unfortunate but true.

Just a note on working around this for anybody getting stuck: the latest LuaRocks release (3.8.0) has a workaround built in to automatically update URLs in any rockspecs it processes. This won't help older LuaRocks versions trying to install order versions of rocks, but if you have the option to update LuaRocks that's one way forward.

**Comment by Frenzie** [comment]
> unfortunately all existing rockspecs must also be updated, and re-uploaded

Is this a request for some kind of change in this PR? As it is nothing works and presumably all of us would like master to Just Work™. ;-)

**Comment by Tieske** [comment]
@Frenzie A newer version of LuaRocks will automatically cover this case. So upgrading should get you unblocked.

@ajacksified The API key I have currently doesn't work, so I cannot fix this issue. If you can send me a new working one, I'll take care of this.

**Review by alerque — APPROVED** [review]
This PR has been taken care of because the SCM rockspec already reflects this change. As noted the backlog of old rockspecs will probably not be updated, although they can be installed fine winh newer Luarocks.

Thanks for the contribution.

**Comment by Frenzie** [comment]
The latest rockspec plus old luarocks matters for convenience, the old rockspec not so much. :-)

**Pull request merged**
