### PR TITLE
Support Korean language

### PR DESCRIPTION
**Pull request by marocchino**

### CODE REVIEW

**Comment by alerque** [comment]
Happy to include this, but we'll also need support added to `say` to make it complete. Can you send a PR there too?

**Comment by alerque** [comment]
https://github.com/lunarmodules/say

**Comment by marocchino** [comment]
Hey @alerque , Thank you for your quick response.
I skimmed through say's code, but couldn't figure out which parts needed fixing. Is there a PR or file I can refer to?

**Comment by alerque** [comment]
My bad, so much for my memory. It wasn't `say` that has strings we use, it is `luassert`. Here is the directory that has translations: https://github.com/lunarmodules/luassert/tree/master/src/languages.

Many/most of those strings can get output by Busted.

**Comment by marocchino** [comment]
https://github.com/lunarmodules/luassert/pull/191

**Review by alerque — APPROVED** [review]

**Pull request merged**
